mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('delete<str:id>', views.post_delete, name='delete'),
    path('edit<str:id>/', views.post_edit, name='post_edit'),
    path('user=<int:id>/', views.profiles, name='profiles'),
    path('<user>/post:<str:id>/', views.post_detail, name='post_detail'),
    path('like/', views.like, name='likes'),
]

mysite/customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'

urlpatterns = [
    # url-адреса регистрации
    path('register/', views.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', views.news, name='news'),
    path('edit/', views.edit, name='edit'),
    path('subscription/', views.subscription, name='subscription'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('customer.urls', namespace='customer')),
    path('oauth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/customer/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    data_of_brith = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users',
                              blank=True)
    subscribers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='subscriptions', blank=True)

    def __str__(self):
        return f'Profile {self.user.username}'

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

mysite/customer/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


''' Форма редактирования данных пользователя '''

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

class ProfileEditForm(forms.ModelForm):

    data_of_brith = forms.DateField(label='дата рождения', widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Profile
        fields = ['data_of_brith', 'photo']

''' Форма регистрации пользователя '''

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Введите пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    username = forms.CharField(label='Логин', widget=forms.TextInput)
    email = forms.CharField(label='Почта', widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Адрес электронной почты уже используется')
        return email

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password2']

mysite/customer/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth.models import User
import logging

from . import services

logger = logging.getLogger(__name__)

''' Обработчик подписки на пользователя '''
@login_required
def subscription(request):
    data = services.user_subscribtion(user=request.user, id=request.POST.get('id'))
    logger.info(('Подписка', data))
    return JsonResponse(data)

''' Представление страницы редактирования профиля '''

@login_required
def edit(request):
    user_form, profile_form = services.edit_profiles(request=request)
    logger.info(('Редактирование', user_form, profile_form))
    return render(request, 'account/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})


''' Представление новостной страницы '''

@login_required
def news(request):
    posts = services.donwloads_posts_in_cache(user=request.user)
    return render(request, 'account/news.html', {'section': 'news', 'post_all': posts})


''' Представление формы регистрации '''

def register(request):
    user = services.user_registration_form(request=request)
    if type(user) is User:
        return render(request, 'account/register_done.html', {'new_user': user})
    logger.info(('Регистрация', user))
    return render(request, 'account/register.html', {'user_form': user})

mysite/customer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}+++{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<script src="https://unpkg.com/@vkid/sdk@latest/dist-sdk/umd/index.js"></script>
<body>
    <div id="header">
        <span class="logo"><a href="{% url 'customer:news' %}">Мир блогов</a></span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "profile" %}class="selected"{% endif %}>
                <a href="{% url 'blog:profiles' request.user.id %}">Профиль</a></li>
            <li {% if section == "edit" %}class="selected"{% endif %}>
                <a href="{% url 'customer:edit' %}">Редактировать профиль</a></li>
        </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                {{ request.user.username|default:request.user.username }}
                <form action="{% url 'customer:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Выход</button>
                </form>
            {% else %}
                <a href="{% url 'customer:login' %}">Вход</a>
            {% endif %}
        </span>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script>
        $(document).ready(function () {
            $('.like').click(function (event) {
                event.preventDefault();
                let postId = this.getAttribute('data-post-id');
                $.ajax({
                    url: '/like/',
                    type: 'POST',
                    data: {'id': postId, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success: function(response) {
                        $('#' + postId).html(response['likes_count']);
                        console.log('Запрос выполнен успешно');
                        console.log(response['likes_count']);
                    },
                    error: function(xhr, status, error) {
                        console.error('Ошибка запроса');
                        console.error(error);
                    }
                });
            });
            });
            $(document).ready(function () {
                $('.subscript').click(function (event) {
                    event.preventDefault();
                    let postId = this.getAttribute('data-post-id');
                    $.ajax({
                        url: '/subscription/',
                        type: 'POST',
                        data: {'id': postId, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: 'json',
                        success: function(response) {
                            $('#' + postId).html(response['sub']);
                            console.log('Запрос выполнен успешно');
                            console.log(response['sub']);
                        },
                        error: function(xhr, status, error) {
                            console.error('Ошибка запроса');
                            console.error(error);
                        }
                    });
                });
            });
    </script>
</body>
</html>