mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('delete<str:id>', views.post_delete, name='delete'),
    path('edit<str:id>/', views.post_edit, name='post_edit'),
    path('user=<int:id>/', views.profiles, name='profiles'),
    path('<user>/post:<str:id>/', views.post_detail, name='post_detail'),
    path('like/', views.like, name='likes'),
]

mysite/customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'

urlpatterns = [
    # url-адреса регистрации
    path('register/', views.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', views.news, name='news'),
    path('edit/', views.edit, name='edit'),
    path('subscription/', views.subscription, name='subscription'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('customer.urls', namespace='customer')),
    path('oauth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


''' Модель поста '''

class UserPost(models.Model):
    title = models.CharField(max_length=250)
    slug = slugify(title)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='post/%Y/%m/%d/', blank=True, null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post', blank=True)


    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.title

    def detail_absolute_url(self):
        return reverse('blog:post_detail', args=[self.user.id, self.id])


''' Модель комментариев '''

class CommentPost(models.Model):
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE, related_name='post_comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f'{self.post} {self.user}'

mysite/blog/forms.py
from django import forms
from .models import UserPost, CommentPost


''' Форма заполнения комментария '''

class CommentForm(forms.ModelForm):

    class Meta:
        model = CommentPost
        fields = ['body']

''' Форма заполнения поста '''

class PostForm(forms.ModelForm):

    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'submit-post', 'placeholder': 'Что у вас нового?'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'submit-title', 'placeholder': 'Название поста'}))

    class Meta:
        model = UserPost
        fields = ['title', 'body', 'image']

mysite/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import logging
from . import services

logger = logging.getLogger(__name__)

''' Представление редактирования поста '''
@login_required
def post_edit(request, id):
    post = services.post_query_database(post_id=id, user_id=request.user.id)
    form = services.form_edit_post(request, post)
    if request.method == 'POST':
        return redirect(request.POST['return_to'])
    data = {'form': form}
    return render(request, 'blog/post_edit.html', data)

''' Представление удаления поста '''
@login_required
def post_delete(request, id):
    post = services.post_query_database(post_id=id, user_id=request.user.id)
    post.delete()
    services.cache_posts_database(request.user.id)
    return redirect(request.META.get('HTTP_REFERER'))


''' Представление лайков поста '''

def like(request):
    data = services.likes_processing(id=(request.POST.get('id')), user=request.user)
    return JsonResponse(data)


''' Детальное представление поста '''

@login_required
def post_detail(request, user, id):
    post = services.post_query_database(user_id=user, post_id=id)
    form = services.save_coment_post(request, post)
    if request.method == 'POST':
            return redirect(f'/post:{id}')
    data = {'post': post, 'form': form, 'comment': services.list_coments_post(post_id=id)}
    return render(request, 'blog/post_detail.html', data)


''' Представление профиля пользователя '''

@login_required
def profiles(request, id):
    users, profiles = services.enquiry_user_profile(user_id=id)
    posts = services.enquiry_posts_list(user_id=id)
    form = services.save_post(request)
    if request.method == 'POST':
        return redirect(f'/user={id}')
    return render(request, 'blog/profiles.html', {'user': users, 'profiles': profiles, 'form': form, 'posts': posts})

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}Представление поста{% endblock %}

{% block content %}
    <div class="detail-post">
        <h1>{{ post.title }}
            <p class="time-detail">{{ post.created }}</p></h1>
        <h2>{{ post.body }}</h2>
        {% if post.image %}
            <img class="img-post" src="{{ post.image.url }}">
        {% endif %}
    </div>
    <div class="table-likes">
        <h2 class="table-title">Список лайкнувших:</h2>
        {% for likes in post.likes.all %}
        <h3>
            <a href="{% url 'blog:profiles' likes.id %}">{{ likes }}</a>
        </h3>
        {% endfor %}
    </div>
    <div class="detail-post">
        <h2>Коментарии:{{ comment.objects.count }}</h2>
        <form method="post" action="{ post.detail_absolute_url }}">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Отправить"></p>
        </form>
    </div>
    <div class="comment-post">
        {% for comments in comment %}
            {% if comments.user.profile.photo.url %}
                <img class="avatar-comment" src="{{ comments.user.profile.photo.url }}">
            {% endif %}
            <h2 class="name-comment">{{ comments.user.username }}</h2>
            <h1 class="body-comment">{{ comments.body }}</h1>
        {% endfor %}
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script>
        $(document).ready(function () {
            $('.edit_post').click(function (event) {
                event.preventDefault();
                let postId = this.getAttribute('data-post-id');
                $.ajax({
                    url: '/edit{{ post.id }}/',
                    type: 'POST',
                    data: {'id': {{ post.id }}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success: function(response) {
                        $('#' + title + postId).html(response['form']['title']);
                        $('#' + body + postId).html(response['form']['body']);
                        console.log('Запрос выполнен успешно');
                        console.log(response['title']);
                    },
                    error: function(xhr, status, error) {
                        console.error('Ошибка запроса');
                        console.error(error);
                    }
                });
            });
        });
    </script>
{% endblock %}

mysite/blog/templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
    <form class="submit-form" method="post" enctype="multipart/form-data">
        {{ form.title }}
        {{ form.body }}
        {{ form.image }}
        {% csrf_token %}
        <input type="hidden" name="return_to"  value="{{ request.META.HTTP_REFERER }}">
        <p><input style="margin-left: 4%;" type="submit" value="Отправить"></p>
    </form>
{% endblock %}

mysite/blog/templates/blog/profiles.html
{% extends "base.html" %}


{% block title %}Мой профиль{% endblock %}

{% block content %}
    <div id="profle-list">
        {% if profiles.photo %}
            <img src="{{ profiles.photo.url }}" id="avatar">
        {% endif %}
        <h2 style="text-align: center;">{{ user.username }}</h2>
        <h3 style="text-align: center;">Родился {{ profiles.data_of_brith }}</h3>
        <h3  style="text-align: center;">Подписчиков : <span id="{{ profiles.user.id }}">{{ profiles.subscribers.count }}</span></h3>
        <h3 style="text-align: center;">Подписки: {{ profiles.user.subscriptions.count }}</h3>
        <form method="post" action="{% url 'customer:subscription' %}">
            {% csrf_token %}
            <button class="subscript" type="submit" data-post-id="{{ profiles.user.id }}">Подписаться</button>
        </form>
    </div>
    <div class="table-sub">
        <h2 class="table-title">Подписчики:</h2>
        {% for subscriber in profiles.subscribers.all %}
        <h3>
            <a style="margin-left: 7px;" href="{% url 'blog:profiles' subscriber.id %}">{{ subscriber }}</a>
        </h3>
        {% endfor %}
    </div>
    <div class="table-subs">
        <h2 class="table-title">Подписки:</h2>
        {% for subscriber in profiles.user.subscriptions.all %}
        <h3>
            <a style="margin-left: 7px;" href="{% url 'blog:profiles' subscriber.user.id %}">{{ subscriber.user }}</a>
        </h3>
        {% endfor %}
    </div>
    {% if request.user.username in user.username %}
        <form class="submit-form" method="post" action="{% url 'blog:profiles' user.id %}" enctype="multipart/form-data">
            {{ form.title }}
            {{ form.body }}
            {{ form.image }}
            {% csrf_token %}
            <p><input style="margin-left: 4%;" type="submit" value="Отправить"></p>
        </form>
    {% endif %}
    <div>
        {% for post in posts %}
            <div class="div-post">
                {% if request.user.username in post.user.username %}
                    <a href="{% url 'blog:post_edit' post.id %}">Редактировать</a>
                    <a href="{% url 'blog:delete' post.id %}">Удалить</a>
                {% endif %}
                <h1>
                    <p class="username-post">{{ post.user.username }}</p>
                    <input type="hidden" name="user"  value="{{ post.user.id }}">
                    <p class="title-post"><a href="{{ post.detail_absolute_url }}">{{ post.title }}</a></p>
                </h1>
                {% if post.image %}
                    <img class="img-post" src="{{ post.image.url }}">
                {% endif %}
                <h2 class="body-post">{{ post.body| truncatewords:15 }}</h2>
                <div>
                    <form action="{% url 'blog:likes' %}" method="post">
                        {% csrf_token %}
                        <p class="likes-post"><button class="like" type="submit" name="pk" data-post-id="{{ post.id }}">Нравится</button> -
                            <span id="{{ post.id }}">{{ post.likes.count }}</span></p>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}